server:
    port: 8888

spring:
    datasource:
        username: root
        password: 123456
        url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
    servlet:
        multipart:
            max-request-size: 10MB
            max-file-size: 10MB

mybatis:
    mapper-locations: classpath:mapping/*.xml

